# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "VM1"

  # your network.
  # config.vm.network "public_network"
  #config.vm.network "private_network", ip: "192.168.56.2", nic_type: "virtio", virtualbox__intnet: "keepcodingsergi"
  #config.vm.network "private_network", ip: "192.168.70.2", :virtualbox__intnet => "keepcodingsergi"
  config.vm.network "private_network", ip: "192.168.70.2"
  #config.vm.network "private_network", ip: "192.168.70.2", nic_type: "virtio", virtualbox__intnet: "keepcodingsergi"
  
  # Reenvío de puerto 80 de la máquina 1 al puerto 8080 del host
  config.vm.network "forwarded_port", guest: 8081, host: 8081

  
  #Script
  config.vm.provision "shell", path: "script_sergi_VM1.sh"

  # Example for VirtualBox:
  #
   config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
    vb.cpus = 1
    vb.memory = "2048"
    file_to_disk = "additional_disk.vdi"
    unless File.exist?(file_to_disk)
        vb.customize ['createhd', '--filename', 'additional_disk.vdi', '--size', '1024']
    end
    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', '1', '--device', '0', '--type', 'hdd', '--medium', 'additional_disk.vdi']


  end
end
